name: Push or Pull request
on:
  push:
  
  pull_request:

jobs:
  push:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install dotnet 7.0
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 7.0.x

      - name: Install packages
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: test
        run: dotnet test --no-restore --verbosity normal